# Generated by Django 4.1.6 on 2023-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Прикрепить фотографию')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('phon', models.IntegerField(verbose_name='Контактный номер')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
    ]
