# Generated by Django 4.1.6 on 2023-04-12 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_stock_time_create'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
