# Generated by Django 4.1.6 on 2023-04-12 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0005_delete_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateField()),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('quantityGoods', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.goods')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.provider')),
            ],
        ),
    ]
