# Generated by Django 4.1.6 on 2023-04-12 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0007_delete_resumeuser_remove_stock_goods_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameGoods', models.CharField(max_length=70)),
                ('descriptionGoods', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ResumeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('age', models.IntegerField(verbose_name='Возраст')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d', verbose_name='Прикрепить фотографию')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. почта')),
                ('phon', models.IntegerField(verbose_name='Контактный номер')),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateField()),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('price', models.IntegerField()),
                ('quantityGoods', models.IntegerField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.goods')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading.provider')),
            ],
        ),
    ]
