# Generated by Django 4.1.6 on 2023-04-12 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0008_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResumeUser',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='goods',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='provider',
        ),
        migrations.DeleteModel(
            name='Vacancies',
        ),
        migrations.DeleteModel(
            name='Goods',
        ),
        migrations.DeleteModel(
            name='Provider',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
