# Generated by Django 4.1.6 on 2023-04-13 18:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trading', '0010_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='goods',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.goods'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.provider'),
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateField()),
                ('price', models.IntegerField()),
                ('quantityGoods', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.goods')),
            ],
        ),
    ]
